### ISSUE TITLE
Min target of iOS 12.0

### ISSUE THREAD

**Issue by marwan87** [zummenix/KeyboardNotificationsObserver#7]
Compiling for iOS 10.0, but module 'KeyboardNotificationsObserver' has a minimum deployment target of iOS 12.0

Is this expected behaviour

**Comment by zummenix** [comment]
Yes, that was intentional on my part. I know it worked well on iOS 12 without issues, so I kept it. If you are still supporting iOS 10, I'd suggest using manual version of installation (i.e. copy the `KeyboardNotificationsObserver.swift` file in your project), and it should work.

**Comment by marwan87** [comment]
Thanks for the quick reply
